using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;

namespace GameEngine.CodeGenerator
{
//    [Generator]
//    public class SourceGenerator : ISourceGenerator
//    {
//        public void Execute(GeneratorExecutionContext context)
//        {
//            // Code generation goes here
//            // Find the main method
//            var mainMethod = context.Compilation.GetEntryPoint(context.CancellationToken);

//            // Build up the source code
//            string source = $@"// <auto-generated/>
//using System;

//namespace {mainMethod.ContainingNamespace.ToDisplayString()}
//{{
//    public static partial class {mainMethod.ContainingType.Name}
//    {{
//        static partial void HelloFrom(string name) =>
//            Console.WriteLine($""Generator says: Hi from '{{name}}'"");
//    }}
//}}
//";
//            var typeName = mainMethod.ContainingType.Name;

//            // Add the source code to the compilation
//            context.AddSource($"{typeName}.g.cs", source);
//        }

//        public void Initialize(GeneratorInitializationContext context)
//        {
//            // No initialization required for this one
//        }
//    }
}
